config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cars
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
  # esta convencion de rails ayuda a poner
  # validaciones sobre los atributos de un modelo
  # en este caso que estos campos sean requeridos
  validates :license_plate, :tint, :model, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(
      license_plate: params[:car][:license_plate],
      model: params[:car][:model],
      tint: params[:car][:tint]
    )
    if @car.save
      redirect_to cars_path
    else
      render :new
    end
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(license_plate: params[:car][:license_plate],
                   model: params[:car][:model],
                   tint: params[:car][:tint])
      redirect_to cars_path
    else
      render :edit
    end
  end

  def destroy
    car = Car.find(params[:id])
    car.destroy

    redirect_to cars_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/edit.html.erb
Editar carro
<%= form_for @car, url: car_path(@car), method: :put do |f| %>
  <%= f.text_field :license_plate, placeholder: 'license_plate' %>
  <%-if f.object.errors[:license_plate].present?%>
    <%= f.object.errors[:license_plate].join(',') %>
  <% end%>

  <%= f.number_field :model, placeholder: 'model' %>
  <%-if f.object.errors[:model].present?%>
    <%= f.object.errors[:model].join(',') %>
  <% end%>

  <%= f.number_field :tint, placeholder: 'model' %>
  <%-if f.object.errors[:tint].present?%>
    <%= f.object.errors[:tint].join(',') %>
  <% end%>
  <%= f.submit 'Actualizar carro' %>
<% end %>

<div>
  <%=link_to 'Ir a listado de carros', cars_path %>
</div>

app/views/cars/index.html.erb
<style>
table, th, td {
  border: 1px solid black;
  border-collapse: collapse;
}
th, td{
 padding: 15px;
}
</style>
Listado de Mis carros
 <table class="default">
    <tr>
    <th>ID</th>
    <th>License Plate</th>
    <th>Model</th>
    <th>Tint</th>
    <th>Editar</th>
    <th>Eliminar</th>
  </tr>
  <%- @cars.each do |car| %>
    <tr>
      <td>
        <%= car.id%>
      </td>
      <td>
        <%= car.license_plate %>
      </td>
      <td>
         <%= car.model %>
      </td>
      <td>
         <%= car.tint %>
      </td>
      <td>
         <%=link_to 'Editar', edit_car_path(car) %>
      </td>
        <td>
         <%==link_to 'Eliminar', car_path(car), method: :delete %>
      </td>
    </tr>
  <% end %>
</table>
<div>
  <%=link_to 'Ir a nuevo Carro', new_car_path  %>
</div>

app/views/cars/new.html.erb
Nuevo carro
<%= form_for @car, url: cars_path, method: :post do |f| %>
  <%= f.text_field :license_plate, placeholder: 'license_plate' %>
  <%-if f.object.errors[:license_plate].present?%>
    <%= f.object.errors[:license_plate].join(',') %>
  <% end%>

  <%= f.number_field :model, placeholder: 'model' %>
  <%-if f.object.errors[:model].present?%>
    <%= f.object.errors[:model].join(',') %>
  <% end%>

  <%= f.number_field :tint, placeholder: 'model' %>
  <%-if f.object.errors[:tint].present?%>
    <%= f.object.errors[:tint].join(',') %>
  <% end%>

  <%= f.submit 'Guardar carro' %>
<% end %>

<div>
  <%=link_to 'Ir a listado de carros', cars_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mayita</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>